# -*- coding: utf-8 -*-

# AUTOMATICALLY GENERATED FILE, DO NOT EDIT

tz_locations = {
    "Brazil": "Brazil",
    "Canada": "Canada",
    "Asia": "Asia",
    "America/Indiana/Tell_City": "Tell City",
    "America/North_Dakota/New_Salem": "New Salem",
    "US": "United States",
    "Indiana": "Indiana",
    "Argentina": "Argentina",
    "Europe": "Europe",
    "Australia": "Australia",
    "America/Indiana/Vevay": "Vevay",
    "Arctic": "Arctic",
    "America/Indiana/Marengo": "Marengo",
    "Atlantic": "Atlantic",
    "Chile": "Chile",
    "America/Indiana/Vincennes": "Vincennes",
    "America": "America",
    "America/North_Dakota/Center": "Center",
    "Kentucky": "Kentucky",
    "Etc": "Etc",
    "North_Dakota": "North Dakota",
    "America/Indiana/Knox": "Knox",
    "America/Kentucky/Monticello": "Monticello",
    "America/North_Dakota/Beulah": "Beulah",
    "America/Indiana/Petersburg": "Petersburg",
    "Mexico": "Mexico",
    "Africa": "Africa",
    "Pacific": "Pacific",
    "Antarctica": "Antarctica",
    "Indian": "Indian",
    "America/Indiana/Winamac": "Winamac",
}

tz_cities = {
    "Atlantic/Canary": "Canary",
    "Australia/Melbourne": "Melbourne",
    "Etc/GMT+9": "GMT+9",
    "Etc/GMT+8": "GMT+8",
    "Europe/Lisbon": "Lisbon",
    "Etc/GMT+3": "GMT+3",
    "Etc/GMT+2": "GMT+2",
    "Etc/GMT+1": "GMT+1",
    "Etc/GMT+0": "GMT+0",
    "America/Nipigon": "Nipigon",
    "Etc/GMT+6": "GMT+6",
    "Etc/GMT+5": "GMT+5",
    "America/Miquelon": "Miquelon",
    "Pacific/Wallis": "Wallis",
    "America/Fort_Nelson": "Fort Nelson",
    "Antarctica/Davis": "Davis",
    "America/Coral_Harbour": "Atikokan",
    "Asia/Dhaka": "Dhaka",
    "America/St_Lucia": "St. Lucia",
    "Canada/Newfoundland": "Newfoundland",
    "Asia/Kashgar": "Kashgar",
    "America/Phoenix": "Phoenix",
    "Europe/Kaliningrad": "Kaliningrad",
    "Etc/GMT+7": "GMT+7",
    "America/Mazatlan": "Mazatlan",
    "Arctic/Longyearbyen": "Longyearbyen",
    "Europe/Guernsey": "Guernsey",
    "GB": "GB",
    "Europe/Paris": "Paris",
    "Europe/Stockholm": "Stockholm",
    "Pacific/Fiji": "Fiji",
    "Pacific/Apia": "Apia",
    "Etc/GMT+4": "GMT+4",
    "Pacific/Pago_Pago": "Pago Pago",
    "Asia/Rangoon": "Rangoon",
    "America/Mexico_City": "Mexico City",
    "America/Ensenada": "Ensenada",
    "America/Puerto_Rico": "Puerto Rico",
    "Indian/Mauritius": "Mauritius",
    "Europe/Berlin": "Berlin",
    "Europe/Zurich": "Zurich",
    "Africa/Casablanca": "Casablanca",
    "Antarctica/Macquarie": "Macquarie Island",
    "Asia/Krasnoyarsk": "Krasnoyarsk",
    "Australia/Canberra": "Canberra",
    "Atlantic/Bermuda": "Bermuda",
    "Asia/Ujung_Pandang": "Ujung Pandang",
    "America/Araguaina": "Araguaina",
    "Asia/Tehran": "Tehran",
    "Asia/Saigon": "Ho Chi Minh",
    "Asia/Baku": "Baku",
    "America/St_Barthelemy": "St. Barthelemy",
    "America/Porto_Acre": "Porto Acre",
    "America/Santarem": "Santarem",
    "America/Argentina/Cordoba": "Cordoba",
    "Libya": "Libya",
    "America/Danmarkshavn": "Danmarkshavn",
    "America/Scoresbysund": "Ittoqqortoormiit",
    "America/Eirunepe": "Eirunepe",
    "America/Caracas": "Caracas",
    "Asia/Baghdad": "Baghdad",
    "Africa/Monrovia": "Monrovia",
    "Atlantic/Stanley": "Stanley",
    "America/St_Vincent": "St. Vincent",
    "Portugal": "Portugal",
    "Europe/Tiraspol": "Tiraspol",
    "America/Vancouver": "Vancouver",
    "Asia/Ho_Chi_Minh": "Ho Chi Minh",
    "Europe/Busingen": "Busingen",
    "Etc/GMT0": "GMT0",
    "Asia/Thimphu": "Thimphu",
    "Africa/Ouagadougou": "Ouagadougou",
    "America/Belize": "Belize",
    "America/Port_of_Spain": "Port of Spain",
    "Greenwich": "Greenwich",
    "Asia/Tashkent": "Tashkent",
    "Asia/Tokyo": "Tokyo",
    "Pacific/Kiritimati": "Kiritimati",
    "Australia/Sydney": "Sydney",
    "Europe/Riga": "Riga",
    "Asia/Dili": "Dili",
    "Africa/Mbabane": "Mbabane",
    "Asia/Oral": "Oral",
    "Asia/Aden": "Aden",
    "Europe/Isle_of_Man": "Isle of Man",
    "Europe/Istanbul": "Istanbul",
    "Asia/Magadan": "Magadan",
    "Australia/Lindeman": "Lindeman",
    "US/Michigan": "Michigan",
    "Pacific/Galapagos": "Galapagos",
    "America/Bogota": "Bogota",
    "Africa/Asmara": "Asmara",
    "America/Chicago": "Chicago",
    "Pacific/Kwajalein": "Kwajalein",
    "Australia/Broken_Hill": "Broken Hill",
    "America/Cuiaba": "Cuiaba",
    "Indian/Christmas": "Christmas",
    "Asia/Jayapura": "Jayapura",
    "Europe/Brussels": "Brussels",
    "Asia/Chongqing": "Chongqing",
    "Australia/NSW": "NSW",
    "Canada/Pacific": "Pacific",
    "America/Noronha": "Noronha",
    "Europe/Podgorica": "Podgorica",
    "Africa/Algiers": "Algiers",
    "Africa/Harare": "Harare",
    "Africa/Ndjamena": "Ndjamena",
    "America/Costa_Rica": "Costa Rica",
    "Europe/Ljubljana": "Ljubljana",
    "Indian/Mayotte": "Mayotte",
    "Asia/Phnom_Penh": "Phnom Penh",
    "America/Managua": "Managua",
    "America/Pangnirtung": "Pangnirtung",
    "Etc/GMT+12": "GMT+12",
    "America/Tijuana": "Tijuana",
    "Pacific/Fakaofo": "Fakaofo",
    "America/Adak": "Adak",
    "America/Antigua": "Antigua",
    "America/Indiana/Indianapolis": "Indianapolis",
    "America/Argentina/La_Rioja": "La Rioja",
    "Pacific/Tahiti": "Tahiti",
    "Asia/Brunei": "Brunei",
    "Europe/Zagreb": "Zagreb",
    "America/Asuncion": "Asuncion",
    "Europe/Vienna": "Vienna",
    "Mexico/General": "General",
    "Australia/Hobart": "Hobart",
    "America/Juneau": "Juneau",
    "America/Inuvik": "Inuvik",
    "America/Ojinaga": "Ojinaga",
    "Europe/Astrakhan": "Astrakhan",
    "America/Montreal": "Montreal",
    "Asia/Seoul": "Seoul",
    "Brazil/East": "East",
    "Indian/Comoro": "Comoro",
    "Antarctica/Rothera": "Rothera",
    "Hongkong": "Hongkong",
    "Europe/Tallinn": "Tallinn",
    "Indian/Mahe": "Mahe",
    "Asia/Calcutta": "Kolkata",
    "Australia/South": "South",
    "America/Argentina/Jujuy": "Jujuy",
    "Asia/Bishkek": "Bishkek",
    "America/Creston": "Creston",
    "America/Martinique": "Martinique",
    "Asia/Singapore": "Singapore",
    "PRC": "PRC",
    "Africa/Nairobi": "Nairobi",
    "Asia/Thimbu": "Thimbu",
    "America/Maceio": "Maceio",
    "Africa/Cairo": "Cairo",
    "Europe/Moscow": "Moscow",
    "Antarctica/Palmer": "Palmer",
    "Asia/Ulaanbaatar": "Ulaanbaatar",
    "America/Rainy_River": "Rainy River",
    "Africa/Kampala": "Kampala",
    "Asia/Colombo": "Colombo",
    "Australia/Adelaide": "Adelaide",
    "America/Cambridge_Bay": "Cambridge Bay",
    "Africa/Luanda": "Luanda",
    "Pacific/Chatham": "Chatham",
    "America/Indiana/Winamac": "Winamac, Indiana",
    "Asia/Dacca": "Dacca",
    "America/Cordoba": "Cordoba",
    "Asia/Tbilisi": "Tbilisi",
    "Europe/Gibraltar": "Gibraltar",
    "Asia/Karachi": "Karachi",
    "Asia/Harbin": "Harbin",
    "Australia/Lord_Howe": "Lord Howe",
    "Etc/GMT-9": "GMT-9",
    "Etc/GMT-8": "GMT-8",
    "America/Bahia_Banderas": "Bahia Banderas",
    "Etc/GMT-1": "GMT-1",
    "Etc/GMT-0": "GMT-0",
    "Etc/GMT-3": "GMT-3",
    "Etc/GMT-2": "GMT-2",
    "Etc/GMT-5": "GMT-5",
    "Etc/GMT-4": "GMT-4",
    "Etc/GMT-7": "GMT-7",
    "Europe/Nicosia": "Nicosia",
    "America/Boa_Vista": "Boa Vista",
    "Eire": "Eire",
    "America/Lima": "Lima",
    "Indian/Reunion": "Reunion",
    "Canada/Mountain": "Mountain",
    "Asia/Srednekolymsk": "Srednekolymsk",
    "CET": "CET",
    "Europe/Belfast": "Belfast",
    "America/Blanc-Sablon": "Blanc-Sablon",
    "Australia/West": "West",
    "Antarctica/Syowa": "Syowa",
    "America/Jamaica": "Jamaica",
    "Europe/Kiev": "Kiev",
    "Europe/Budapest": "Budapest",
    "Canada/Eastern": "Eastern",
    "Pacific/Midway": "Midway",
    "America/Goose_Bay": "Goose Bay",
    "Australia/Victoria": "Victoria",
    "Asia/Amman": "Amman",
    "Asia/Sakhalin": "Sakhalin",
    "Africa/Windhoek": "Windhoek",
    "US/Pacific": "Pacific",
    "America/Sitka": "Sitka",
    "Asia/Katmandu": "Kathmandu",
    "America/Guyana": "Guyana",
    "Pacific/Pohnpei": "Pohnpei",
    "America/Sao_Paulo": "Sao Paulo",
    "Turkey": "Turkey",
    "Australia/Yancowinna": "Yancowinna",
    "America/Lower_Princes": "Lower Prince’s Quarter",
    "Australia/Perth": "Perth",
    "Africa/Djibouti": "Djibouti",
    "Asia/Jakarta": "Jakarta",
    "Asia/Pyongyang": "Pyongyang",
    "EST5EDT": "EST5EDT",
    "Africa/Johannesburg": "Johannesburg",
    "Canada/East-Saskatchewan": "East-Saskatchewan",
    "Asia/Tel_Aviv": "Tel Aviv",
    "Antarctica/Troll": "Troll",
    "Asia/Istanbul": "Istanbul",
    "Asia/Irkutsk": "Irkutsk",
    "Iran": "Iran",
    "Australia/ACT": "ACT",
    "Africa/Niamey": "Niamey",
    "Australia/North": "North",
    "America/Belem": "Belem",
    "America/Indiana/Marengo": "Marengo, Indiana",
    "Africa/Nouakchott": "Nouakchott",
    "Asia/Ashkhabad": "Ashkhabad",
    "Europe/Vilnius": "Vilnius",
    "America/Cayenne": "Cayenne",
    "Africa/Mogadishu": "Mogadishu",
    "America/Kentucky/Monticello": "Monticello, Kentucky",
    "America/Rio_Branco": "Rio Branco",
    "America/Cancun": "Cancun",
    "America/Havana": "Havana",
    "Chile/EasterIsland": "EasterIsland",
    "Pacific/Guam": "Guam",
    "Pacific/Kosrae": "Kosrae",
    "Universal": "Universal",
    "US/Arizona": "Arizona",
    "Atlantic/Azores": "Azores",
    "Australia/Eucla": "Eucla",
    "Asia/Shanghai": "Shanghai",
    "US/Alaska": "Alaska",
    "America/Godthab": "Nuuk",
    "Asia/Beirut": "Beirut",
    "Africa/Maputo": "Maputo",
    "HST": "HST",
    "Asia/Bahrain": "Bahrain",
    "Asia/Ashgabat": "Ashgabat",
    "Asia/Riyadh": "Riyadh",
    "Atlantic/Faeroe": "Faroe",
    "America/Montevideo": "Montevideo",
    "America/Anguilla": "Anguilla",
    "Asia/Damascus": "Damascus",
    "America/North_Dakota/Center": "Center, North Dakota",
    "UCT": "UCT",
    "America/Indiana/Vevay": "Vevay, Indiana",
    "Atlantic/St_Helena": "St. Helena",
    "Iceland": "Iceland",
    "Europe/Vatican": "Vatican",
    "America/Indiana/Vincennes": "Vincennes, Indiana",
    "Asia/Almaty": "Almaty",
    "Australia/Queensland": "Queensland",
    "America/Santo_Domingo": "Santo Domingo",
    "Africa/Brazzaville": "Brazzaville",
    "America/Nome": "Nome",
    "Asia/Taipei": "Taipei",
    "America/Yakutat": "Yakutat",
    "W-SU": "W-SU",
    "America/Argentina/Mendoza": "Mendoza",
    "Zulu": "Zulu",
    "Egypt": "Egypt",
    "America/Tortola": "Tortola",
    "Etc/UTC": "UTC",
    "Brazil/Acre": "Acre",
    "Africa/Asmera": "Asmara",
    "Antarctica/Mawson": "Mawson",
    "America/Buenos_Aires": "Buenos Aires",
    "Asia/Kolkata": "Kolkata",
    "Africa/Maseru": "Maseru",
    "America/Atikokan": "Atikokan",
    "America/Louisville": "Louisville",
    "Pacific/Yap": "Yap",
    "America/Santa_Isabel": "Santa Isabel",
    "Asia/Kuching": "Kuching",
    "Africa/Libreville": "Libreville",
    "Africa/Freetown": "Freetown",
    "Africa/Bissau": "Bissau",
    "Europe/Samara": "Samara",
    "Europe/Amsterdam": "Amsterdam",
    "Europe/Tirane": "Tirane",
    "Pacific/Saipan": "Saipan",
    "Africa/Abidjan": "Abidjan",
    "Europe/Zaporozhye": "Zaporozhye",
    "America/Atka": "Atka",
    "America/El_Salvador": "El Salvador",
    "Europe/Madrid": "Madrid",
    "Africa/Juba": "Juba",
    "America/Santiago": "Santiago",
    "America/Argentina/Buenos_Aires": "Buenos Aires",
    "America/Argentina/San_Luis": "San Luis",
    "Europe/Skopje": "Skopje",
    "WET": "WET",
    "America/Aruba": "Aruba",
    "Navajo": "Navajo",
    "America/Indianapolis": "Indianapolis",
    "America/Regina": "Regina",
    "Pacific/Truk": "Chuuk",
    "Pacific/Chuuk": "Chuuk",
    "Asia/Khandyga": "Khandyga",
    "Pacific/Funafuti": "Funafuti",
    "Canada/Atlantic": "Atlantic",
    "America/Merida": "Merida",
    "America/Guatemala": "Guatemala",
    "Africa/Sao_Tome": "Sao Tome",
    "Asia/Tomsk": "Tomsk",
    "Asia/Makassar": "Makassar",
    "Africa/Bujumbura": "Bujumbura",
    "Europe/Chisinau": "Chisinau",
    "Europe/Warsaw": "Warsaw",
    "Asia/Yekaterinburg": "Yekaterinburg",
    "US/Hawaii": "Hawaii",
    "MET": "MET",
    "Antarctica/Casey": "Casey",
    "Pacific/Enderbury": "Enderbury",
    "America/Thule": "Thule",
    "America/St_Johns": "St. John’s",
    "America/Moncton": "Moncton",
    "Europe/Helsinki": "Helsinki",
    "Atlantic/Cape_Verde": "Cape Verde",
    "America/Tegucigalpa": "Tegucigalpa",
    "Indian/Cocos": "Cocos",
    "America/Boise": "Boise",
    "America/Guadeloupe": "Guadeloupe",
    "America/Nassau": "Nassau",
    "Europe/Prague": "Prague",
    "America/Halifax": "Halifax",
    "Asia/Hovd": "Hovd",
    "Canada/Saskatchewan": "Saskatchewan",
    "America/Manaus": "Manaus",
    "America/Rankin_Inlet": "Rankin Inlet",
    "Etc/UCT": "UCT",
    "GB-Eire": "GB-Eire",
    "Etc/Greenwich": "Greenwich",
    "Atlantic/Jan_Mayen": "Jan Mayen",
    "America/North_Dakota/Beulah": "Beulah, North Dakota",
    "America/Chihuahua": "Chihuahua",
    "America/Iqaluit": "Iqaluit",
    "America/Argentina/Rio_Gallegos": "Rio Gallegos",
    "Pacific/Gambier": "Gambier",
    "Europe/Volgograd": "Volgograd",
    "Africa/Bamako": "Bamako",
    "Asia/Novokuznetsk": "Novokuznetsk",
    "Europe/Uzhgorod": "Uzhgorod",
    "Africa/Banjul": "Banjul",
    "Asia/Aqtau": "Aqtau",
    "Pacific/Palau": "Palau",
    "Africa/Malabo": "Malabo",
    "Europe/Minsk": "Minsk",
    "PST8PDT": "PST8PDT",
    "America/Argentina/ComodRivadavia": "ComodRivadavia",
    "Atlantic/Madeira": "Madeira",
    "Pacific/Noumea": "Noumea",
    "GMT0": "GMT0",
    "Africa/Kinshasa": "Kinshasa",
    "Europe/Malta": "Malta",
    "US/Samoa": "Samoa",
    "America/Argentina/Ushuaia": "Ushuaia",
    "Asia/Chungking": "Chungking",
    "Asia/Bangkok": "Bangkok",
    "Pacific/Niue": "Niue",
    "America/Catamarca": "Catamarca",
    "America/Recife": "Recife",
    "MST": "MST",
    "Asia/Yerevan": "Yerevan",
    "America/La_Paz": "La Paz",
    "Poland": "Poland",
    "Asia/Urumqi": "Urumqi",
    "Africa/Lusaka": "Lusaka",
    "US/Indiana-Starke": "Indiana-Starke",
    "Pacific/Guadalcanal": "Guadalcanal",
    "America/Yellowknife": "Yellowknife",
    "Australia/LHI": "LHI",
    "Asia/Vientiane": "Vientiane",
    "Asia/Kuwait": "Kuwait",
    "Africa/Conakry": "Conakry",
    "Asia/Dubai": "Dubai",
    "America/Argentina/Tucuman": "Tucuman",
    "Asia/Chita": "Chita",
    "Europe/Oslo": "Oslo",
    "Australia/Currie": "Currie",
    "America/St_Kitts": "St. Kitts",
    "America/Panama": "Panama",
    "America/Hermosillo": "Hermosillo",
    "Asia/Hebron": "Hebron",
    "America/Guayaquil": "Guayaquil",
    "Asia/Kuala_Lumpur": "Kuala Lumpur",
    "Europe/London": "London",
    "America/Menominee": "Menominee",
    "Asia/Kamchatka": "Kamchatka",
    "Europe/Ulyanovsk": "Ulyanovsk",
    "Asia/Vladivostok": "Vladivostok",
    "America/Matamoros": "Matamoros",
    "Brazil/DeNoronha": "DeNoronha",
    "Asia/Qatar": "Qatar",
    "Israel": "Israel",
    "NZ-CHAT": "NZ-CHAT",
    "Asia/Dushanbe": "Dushanbe",
    "Asia/Yakutsk": "Yakutsk",
    "Asia/Omsk": "Omsk",
    "Africa/Bangui": "Bangui",
    "UTC": "UTC",
    "America/Paramaribo": "Paramaribo",
    "Etc/GMT-11": "GMT-11",
    "Etc/GMT-10": "GMT-10",
    "Etc/GMT-13": "GMT-13",
    "Etc/GMT-12": "GMT-12",
    "Etc/GMT-14": "GMT-14",
    "Pacific/Marquesas": "Marquesas",
    "US/Central": "Central",
    "Europe/Bratislava": "Bratislava",
    "Asia/Anadyr": "Anadyr",
    "America/New_York": "New York",
    "Pacific/Norfolk": "Norfolk",
    "CST6CDT": "CST6CDT",
    "Pacific/Rarotonga": "Rarotonga",
    "America/Dominica": "Dominica",
    "Africa/Porto-Novo": "Porto-Novo",
    "Asia/Samarkand": "Samarkand",
    "America/Kentucky/Louisville": "Louisville",
    "America/Toronto": "Toronto",
    "America/Bahia": "Bahia",
    "Indian/Maldives": "Maldives",
    "Africa/Accra": "Accra",
    "Antarctica/South_Pole": "South Pole",
    "Asia/Muscat": "Muscat",
    "America/Virgin": "Virgin",
    "America/Edmonton": "Edmonton",
    "Pacific/Wake": "Wake",
    "America/Indiana/Tell_City": "Tell City, Indiana",
    "Australia/Darwin": "Darwin",
    "America/Whitehorse": "Whitehorse",
    "America/Swift_Current": "Swift Current",
    "Europe/Copenhagen": "Copenhagen",
    "America/Fort_Wayne": "Fort Wayne",
    "America/Montserrat": "Montserrat",
    "America/Mendoza": "Mendoza",
    "US/Mountain": "Mountain",
    "Europe/Simferopol": "Simferopol",
    "Africa/Blantyre": "Blantyre",
    "America/Detroit": "Detroit",
    "America/Shiprock": "Shiprock",
    "America/Grenada": "Grenada",
    "Atlantic/Faroe": "Faroe",
    "America/Indiana/Petersburg": "Petersburg, Indiana",
    "Asia/Kathmandu": "Kathmandu",
    "Asia/Pontianak": "Pontianak",
    "Jamaica": "Jamaica",
    "Europe/Athens": "Athens",
    "America/Port-au-Prince": "Port-au-Prince",
    "America/Cayman": "Cayman",
    "Etc/Universal": "Universal",
    "Africa/Dar_es_Salaam": "Dar es Salaam",
    "America/Curacao": "Curacao",
    "Indian/Kerguelen": "Kerguelen",
    "Africa/Khartoum": "Khartoum",
    "Asia/Manila": "Manila",
    "Africa/Lome": "Lome",
    "America/Jujuy": "Jujuy",
    "Africa/Douala": "Douala",
    "EET": "EET",
    "America/Argentina/San_Juan": "San Juan",
    "America/North_Dakota/New_Salem": "New Salem, North Dakota",
    "America/Kralendijk": "Kralendijk",
    "Pacific/Port_Moresby": "Port Moresby",
    "Europe/Jersey": "Jersey",
    "Asia/Macao": "Macao",
    "Europe/Andorra": "Andorra",
    "ROK": "ROK",
    "Cuba": "Cuba",
    "Europe/Luxembourg": "Luxembourg",
    "Pacific/Honolulu": "Honolulu",
    "ROC": "ROC",
    "America/St_Thomas": "St. Thomas",
    "Pacific/Majuro": "Majuro",
    "Asia/Hong_Kong": "Hong Kong",
    "Asia/Macau": "Macau",
    "MST7MDT": "MST7MDT",
    "Europe/Belgrade": "Belgrade",
    "Asia/Choibalsan": "Choibalsan",
    "US/Eastern": "Eastern",
    "Europe/Mariehamn": "Mariehamn",
    "Antarctica/McMurdo": "McMurdo",
    "America/Thunder_Bay": "Thunder Bay",
    "America/Los_Angeles": "Los Angeles",
    "Asia/Kabul": "Kabul",
    "Indian/Antananarivo": "Antananarivo",
    "Europe/Sarajevo": "Sarajevo",
    "Atlantic/Reykjavik": "Reykjavik",
    "Asia/Nicosia": "Nicosia",
    "Etc/GMT+11": "GMT+11",
    "Etc/GMT+10": "GMT+10",
    "Pacific/Ponape": "Pohnpei",
    "Japan": "Japan",
    "Asia/Ulan_Bator": "Ulan Bator",
    "Asia/Barnaul": "Barnaul",
    "Kwajalein": "Kwajalein",
    "Pacific/Tongatapu": "Tongatapu",
    "America/Marigot": "Marigot",
    "Pacific/Pitcairn": "Pitcairn",
    "Pacific/Easter": "Easter Island",
    "US/East-Indiana": "East-Indiana",
    "Atlantic/South_Georgia": "South Georgia",
    "Africa/El_Aaiun": "El Aaiun",
    "US/Pacific-New": "Pacific-New",
    "Chile/Continental": "Continental",
    "Europe/Kirov": "Kirov",
    "America/Campo_Grande": "Campo Grande",
    "America/Dawson_Creek": "Dawson Creek",
    "America/Rosario": "Rosario",
    "Antarctica/Vostok": "Vostok",
    "US/Aleutian": "Aleutian",
    "Europe/Bucharest": "Bucharest",
    "America/Porto_Velho": "Porto Velho",
    "Europe/Monaco": "Monaco",
    "NZ": "NZ",
    "Africa/Ceuta": "Ceuta",
    "Europe/Rome": "Rome",
    "America/Winnipeg": "Winnipeg",
    "America/Knox_IN": "Knox IN",
    "Asia/Aqtobe": "Aqtobe",
    "Africa/Dakar": "Dakar",
    "America/Fortaleza": "Fortaleza",
    "Pacific/Samoa": "Samoa",
    "Pacific/Tarawa": "Tarawa",
    "America/Dawson": "Dawson",
    "Africa/Addis_Ababa": "Addis Ababa",
    "Pacific/Efate": "Efate",
    "Pacific/Johnston": "Johnston",
    "GMT": "GMT",
    "Australia/Brisbane": "Brisbane",
    "Canada/Yukon": "Yukon",
    "Asia/Qyzylorda": "Qyzylorda",
    "Europe/San_Marino": "San Marino",
    "Asia/Jerusalem": "Jerusalem",
    "America/Barbados": "Barbados",
    "Pacific/Auckland": "Auckland",
    "America/Metlakatla": "Metlakatla",
    "Etc/Zulu": "Zulu",
    "America/Denver": "Denver",
    "Indian/Chagos": "Chagos",
    "America/Glace_Bay": "Glace Bay",
    "Pacific/Bougainville": "Bougainville Island",
    "Africa/Gaborone": "Gaborone",
    "Africa/Tunis": "Tunis",
    "Australia/Tasmania": "Tasmania",
    "Asia/Ust-Nera": "Ust-Nera",
    "Europe/Vaduz": "Vaduz",
    "Africa/Lubumbashi": "Lubumbashi",
    "America/Resolute": "Resolute",
    "Etc/GMT": "GMT",
    "Asia/Gaza": "Gaza",
    "Europe/Dublin": "Dublin",
    "GMT+0": "GMT+0",
    "Antarctica/DumontDUrville": "Dumont d’Urville",
    "America/Argentina/Catamarca": "Catamarca",
    "America/Indiana/Knox": "Knox, Indiana",
    "Etc/GMT-6": "GMT-6",
    "Africa/Timbuktu": "Timbuktu",
    "Asia/Novosibirsk": "Novosibirsk",
    "EST": "EST",
    "Mexico/BajaNorte": "BajaNorte",
    "Africa/Kigali": "Kigali",
    "Brazil/West": "West",
    "America/Grand_Turk": "Grand Turk",
    "Mexico/BajaSur": "BajaSur",
    "America/Argentina/Salta": "Salta",
    "Canada/Central": "Central",
    "Africa/Lagos": "Lagos",
    "GMT-0": "GMT-0",
    "Europe/Sofia": "Sofia",
    "Singapore": "Singapore",
    "Africa/Tripoli": "Tripoli",
    "America/Anchorage": "Anchorage",
    "America/Monterrey": "Monterrey",
    "Pacific/Nauru": "Nauru",
}

territories = {
    "BD": "Bangladesh",
    "BE": "Belgium",
    "BF": "Burkina Faso",
    "BG": "Bulgaria",
    "VE": "Venezuela",
    "BA": "Bosnia & Herzegovina",
    "BB": "Barbados",
    "WF": "Wallis & Futuna",
    "BL": "St. Barthélemy",
    "BM": "Bermuda",
    "BN": "Brunei",
    "BO": "Bolivia",
    "BH": "Bahrain",
    "BI": "Burundi",
    "BJ": "Benin",
    "BT": "Bhutan",
    "011": "Western Africa",
    "BV": "Bouvet Island",
    "BW": "Botswana",
    "014": "Eastern Africa",
    "015": "Northern Africa",
    "BR": "Brazil",
    "017": "Middle Africa",
    "018": "Southern Africa",
    "019": "Americas",
    "BY": "Belarus",
    "BZ": "Belize",
    "LV": "Latvia",
    "RW": "Rwanda",
    "RS": "Serbia",
    "TL": "Timor-Leste",
    "RE": "Réunion",
    "TM": "Turkmenistan",
    "OM": "Oman",
    "TJ": "Tajikistan",
    "RO": "Romania",
    "TK": "Tokelau",
    "GW": "Guinea-Bissau",
    "GU": "Guam",
    "GT": "Guatemala",
    "GS": "South Georgia & South Sandwich Islands",
    "GR": "Greece",
    "GQ": "Equatorial Guinea",
    "GP": "Guadeloupe",
    "JP": "Japan",
    "KI": "Kiribati",
    "GY": "Guyana",
    "GG": "Guernsey",
    "GF": "French Guiana",
    "GE": "Georgia",
    "GD": "Grenada",
    "021": "Northern America",
    "GB": "United Kingdom",
    "GA": "Gabon",
    "SV": "El Salvador",
    "GN": "Guinea",
    "GM": "Gambia",
    "GL": "Greenland",
    "029": "Caribbean",
    "GI": "Gibraltar",
    "GH": "Ghana",
    "JE": "Jersey",
    "TN": "Tunisia",
    "JM": "Jamaica",
    "013": "Central America",
    "WS": "Samoa",
    "TA": "Tristan da Cunha",
    "419": "Latin America",
    "BQ": "Caribbean Netherlands",
    "HR": "Croatia",
    "BS": "Bahamas",
    "HT": "Haiti",
    "HU": "Hungary",
    "HK": "Hong Kong SAR China",
    "039": "Southern Europe",
    "HN": "Honduras",
    "FI": "Finland",
    "142": "Asia",
    "030": "Eastern Asia",
    "034": "Southern Asia",
    "035": "Southeast Asia",
    "PR": "Puerto Rico",
    "PS": "Palestinian Territories",
    "FK": "Falkland Islands",
    "IO": "British Indian Ocean Territory",
    "PW": "Palau",
    "PT": "Portugal",
    "SJ": "Svalbard & Jan Mayen",
    "MD": "Moldova",
    "IQ": "Iraq",
    "PA": "Panama",
    "PF": "French Polynesia",
    "PG": "Papua New Guinea",
    "PE": "Peru",
    "PK": "Pakistan",
    "PH": "Philippines",
    "FO": "Faroe Islands",
    "PN": "Pitcairn Islands",
    "PL": "Poland",
    "PM": "St. Pierre & Miquelon",
    "ZM": "Zambia",
    "EH": "Western Sahara",
    "RU": "Russia",
    "EE": "Estonia",
    "EG": "Egypt",
    "EA": "Ceuta & Melilla",
    "ZA": "South Africa",
    "EC": "Ecuador",
    "IT": "Italy",
    "VN": "Vietnam",
    "ZZ": "Unknown Region",
    "SB": "Solomon Islands",
    "EU": "European Union",
    "ET": "Ethiopia",
    "SO": "Somalia",
    "ZW": "Zimbabwe",
    "SA": "Saudi Arabia",
    "ES": "Spain",
    "ER": "Eritrea",
    "ME": "Montenegro",
    "AQ": "Antarctica",
    "MG": "Madagascar",
    "MF": "St. Martin",
    "MA": "Morocco",
    "MC": "Monaco",
    "UZ": "Uzbekistan",
    "MM": "Myanmar (Burma)",
    "ML": "Mali",
    "MO": "Macau SAR China",
    "MN": "Mongolia",
    "HM": "Heard & McDonald Islands",
    "AS": "American Samoa",
    "MK": "Macedonia",
    "MU": "Mauritius",
    "MT": "Malta",
    "MW": "Malawi",
    "MV": "Maldives",
    "MQ": "Martinique",
    "MP": "Northern Mariana Islands",
    "MS": "Montserrat",
    "MR": "Mauritania",
    "IM": "Isle of Man",
    "UG": "Uganda",
    "TZ": "Tanzania",
    "MY": "Malaysia",
    "MX": "Mexico",
    "IL": "Israel",
    "IC": "Canary Islands",
    "FR": "France",
    "AW": "Aruba",
    "DO": "Dominican Republic",
    "SH": "St. Helena",
    "VC": "St. Vincent & Grenadines",
    "054": "Melanesia",
    "DJ": "Djibouti",
    "FJ": "Fiji",
    "057": "Micronesian Region",
    "FM": "Micronesia",
    "053": "Australasia",
    "NI": "Nicaragua",
    "NL": "Netherlands",
    "NO": "Norway",
    "NA": "Namibia",
    "VU": "Vanuatu",
    "NC": "New Caledonia",
    "NE": "Niger",
    "NF": "Norfolk Island",
    "NG": "Nigeria",
    "NZ": "New Zealand",
    "NP": "Nepal",
    "NR": "Nauru",
    "NU": "Niue",
    "061": "Polynesia",
    "XK": "Kosovo",
    "CI": "Côte d’Ivoire",
    "CH": "Switzerland",
    "CO": "Colombia",
    "CN": "China",
    "CM": "Cameroon",
    "CL": "Chile",
    "CC": "Cocos (Keeling) Islands",
    "CA": "Canada",
    "CG": "Congo - Brazzaville",
    "CF": "Central African Republic",
    "CD": "Congo - Kinshasa",
    "CZ": "Czech Republic",
    "CY": "Cyprus",
    "CX": "Christmas Island",
    "CR": "Costa Rica",
    "PY": "Paraguay",
    "CP": "Clipperton Island",
    "CW": "Curaçao",
    "CV": "Cape Verde",
    "CU": "Cuba",
    "SZ": "Swaziland",
    "SY": "Syria",
    "SX": "Sint Maarten",
    "KG": "Kyrgyzstan",
    "KE": "Kenya",
    "SS": "South Sudan",
    "SR": "Suriname",
    "143": "Central Asia",
    "KH": "Cambodia",
    "KN": "St. Kitts & Nevis",
    "KM": "Comoros",
    "ST": "São Tomé & Príncipe",
    "SK": "Slovakia",
    "KR": "South Korea",
    "SI": "Slovenia",
    "KP": "North Korea",
    "KW": "Kuwait",
    "SN": "Senegal",
    "SM": "San Marino",
    "SL": "Sierra Leone",
    "SC": "Seychelles",
    "KZ": "Kazakhstan",
    "KY": "Cayman Islands",
    "SG": "Singapore",
    "SE": "Sweden",
    "SD": "Sudan",
    "151": "Eastern Europe",
    "150": "Europe",
    "DM": "Dominica",
    "155": "Western Europe",
    "154": "Northern Europe",
    "VG": "British Virgin Islands",
    "DG": "Diego Garcia",
    "DE": "Germany",
    "YE": "Yemen",
    "MH": "Marshall Islands",
    "DZ": "Algeria",
    "US": "United States",
    "UY": "Uruguay",
    "YT": "Mayotte",
    "UM": "U.S. Outlying Islands",
    "LB": "Lebanon",
    "LC": "St. Lucia",
    "LA": "Laos",
    "TV": "Tuvalu",
    "TW": "Taiwan",
    "TT": "Trinidad & Tobago",
    "TR": "Turkey",
    "LK": "Sri Lanka",
    "LI": "Liechtenstein",
    "CK": "Cook Islands",
    "TO": "Tonga",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "LR": "Liberia",
    "LS": "Lesotho",
    "TH": "Thailand",
    "TF": "French Southern Territories",
    "TG": "Togo",
    "TD": "Chad",
    "TC": "Turks & Caicos Islands",
    "LY": "Libya",
    "VA": "Vatican City",
    "AC": "Ascension Island",
    "145": "Western Asia",
    "AE": "United Arab Emirates",
    "AD": "Andorra",
    "AG": "Antigua & Barbuda",
    "AF": "Afghanistan",
    "AI": "Anguilla",
    "VI": "U.S. Virgin Islands",
    "IS": "Iceland",
    "IR": "Iran",
    "AM": "Armenia",
    "AL": "Albania",
    "AO": "Angola",
    "003": "North America",
    "002": "Africa",
    "001": "World",
    "AR": "Argentina",
    "AU": "Australia",
    "AT": "Austria",
    "005": "South America",
    "IN": "India",
    "AX": "Åland Islands",
    "009": "Oceania",
    "AZ": "Azerbaijan",
    "IE": "Ireland",
    "ID": "Indonesia",
    "JO": "Jordan",
    "UA": "Ukraine",
    "QA": "Qatar",
    "DK": "Denmark",
    "MZ": "Mozambique",
    "QO": "Outlying Oceania",
}
